export type LocationType =
  | "airport"
  | "city"
  | "country"
  | "region"
  | "continent";

export type LocationEntry = {
  id: string;
  type: LocationType;
  label: string;
  /** Direct IATA codes owned by this entry. */
  airports?: string[];
  /** Other registry ids to compose recursively. */
  refs?: string[];
};

/** Registry id for the worldwide top-125 airport set. */
export const ANYWHERE_LOCATION_ID = "anywhere";

/**
 * Composable location registry. "usa" appears only here as registry data.
 * Resolution is recursive with cycle detection (see LocationResolver).
 */
export const LOCATION_REGISTRY: Record<string, LocationEntry> = {
  anywhere: {
    id: ANYWHERE_LOCATION_ID,
    type: "continent",
    label: "Anywhere (top 125 airports)",
    // Approximate world top 125 by passenger traffic from Wikipedia/ACI
    // regional rankings (2024–2025) and FAA enplanements.
    airports: [
      "ATL",
      "DXB",
      "HND",
      "DFW",
      "PVG",
      "ORD",
      "LHR",
      "IST",
      "CAN",
      "DEN",
      "DEL",
      "ICN",
      "LAX",
      "CDG",
      "PEK",
      "SIN",
      "AMS",
      "MAD",
      "SZX",
      "KUL",
      "FRA",
      "BKK",
      "JFK",
      "HKG",
      "MCO",
      "BCN",
      "TFU",
      "BOM",
      "MIA",
      "LAS",
      "CGK",
      "SFO",
      "DOH",
      "CLT",
      "PKX",
      "JED",
      "SEA",
      "MNL",
      "PHX",
      "FCO",
      "HGH",
      "SHA",
      "CKG",
      "KMG",
      "XIY",
      "SAW",
      "IAH",
      "TPE",
      "YYZ",
      "GRU",
      "EWR",
      "BOG",
      "MEX",
      "LGW",
      "BOS",
      "SGN",
      "FLL",
      "MUC",
      "AYT",
      "MSP",
      "CUN",
      "CJU",
      "ORY",
      "SYD",
      "LGA",
      "CTU",
      "SVO",
      "DME",
      "DTW",
      "GMP",
      "SLC",
      "CSX",
      "CGO",
      "NKG",
      "XMN",
      "KWE",
      "HAK",
      "HAN",
      "NRT",
      "DMK",
      "MEL",
      "PHL",
      "DUB",
      "ZRH",
      "CPH",
      "KIX",
      "PMI",
      "MAN",
      "OSL",
      "LIS",
      "ARN",
      "BWI",
      "STN",
      "BLR",
      "RUH",
      "BRU",
      "DUS",
      "VIE",
      "YVR",
      "AUH",
      "ATH",
      "MXP",
      "WUH",
      "IAD",
      "AGP",
      "LIM",
      "BER",
      "SCL",
      "SAN",
      "BNA",
      "TPA",
      "WAW",
      "DCA",
      "VKO",
      "CGH",
      "HEL",
      "AUS",
      "HNL",
      "LED",
      "PTY",
      "MDW",
      "LTN",
      "PDX",
      "GVA",
      "GDL",
    ],
  },
  "buenos-aires": {
    id: "buenos-aires",
    type: "city",
    label: "Buenos Aires (all airports)",
    airports: ["EZE", "AEP"],
  },
  london: {
    id: "london",
    type: "city",
    label: "London (all airports)",
    airports: ["LHR", "LGW", "STN", "LTN", "LCY", "SEN"],
  },
  madrid: {
    id: "madrid",
    type: "city",
    label: "Madrid (all airports)",
    airports: ["MAD"],
  },
  seattle: {
    id: "seattle",
    type: "city",
    label: "Seattle (all airports)",
    airports: ["SEA", "PAE", "BFI"],
  },
  "san-francisco": {
    id: "san-francisco",
    type: "city",
    label: "SF (all airports)",
    airports: ["SFO", "OAK", "SJC"],
  },
  "new-york": {
    id: "new-york",
    type: "city",
    label: "NYC (all airports)",
    airports: ["JFK", "LGA", "EWR"],
  },
  tashkent: {
    id: "tashkent",
    type: "city",
    label: "Tashkent (all airports)",
    airports: ["TAS", "TVT"],
  },
  prague: {
    id: "prague",
    type: "city",
    label: "Prague (all airports)",
    airports: ["PRG", "VOD"],
  },
  "usa-gateways": {
    id: "usa-gateways",
    type: "country",
    label: "USA gateways",
    // Top 35 US airports by 2024 total passenger traffic (ACI-NA).
    airports: [
      "ATL",
      "DFW",
      "DEN",
      "ORD",
      "LAX",
      "JFK",
      "CLT",
      "LAS",
      "MCO",
      "MIA",
      "SEA",
      "PHX",
      "SFO",
      "EWR",
      "IAH",
      "BOS",
      "MSP",
      "FLL",
      "LGA",
      "DTW",
      "PHL",
      "SLC",
      "BWI",
      "IAD",
      "DCA",
      "SAN",
      "TPA",
      "BNA",
      "HNL",
      "AUS",
      "MDW",
      "DAL",
      "PDX",
      "STL",
      "RDU",
    ],
  },
  "canada-gateways": {
    id: "canada-gateways",
    type: "country",
    label: "Canada gateways",
    // Top 6 Canadian airports by 2024 passenger traffic.
    airports: ["YYZ", "YVR", "YUL", "YYC", "YEG", "YOW"],
  },
  "uk-ireland-gateways": {
    id: "uk-ireland-gateways",
    type: "region",
    label: "UK/Ireland gateways",
    // Combined top 10 by 2024 passenger traffic.
    airports: [
      "LHR",
      "LGW",
      "DUB",
      "MAN",
      "STN",
      "LTN",
      "EDI",
      "BHX",
      "BRS",
      "GLA",
    ],
  },
  "schengen-eu-gateways": {
    id: "schengen-eu-gateways",
    type: "region",
    label: "Schengen/EU gateways",
    // Top 40 Schengen-area airports by 2024 passenger traffic.
    airports: [
      "CDG",
      "AMS",
      "MAD",
      "FRA",
      "BCN",
      "FCO",
      "MUC",
      "LIS",
      "PMI",
      "ORY",
      "ATH",
      "VIE",
      "ZRH",
      "CPH",
      "MXP",
      "OSL",
      "BER",
      "AGP",
      "BRU",
      "ARN",
      "WAW",
      "DUS",
      "ALC",
      "GVA",
      "BUD",
      "BGY",
      "PRG",
      "HEL",
      "OTP",
      "OPO",
      "HAM",
      "NCE",
      "NAP",
      "CTA",
      "VCE",
      "MRS",
      "KRK",
      "VLC",
      "BLQ",
      "LIN",
    ],
  },
  "mexico-gateways": {
    id: "mexico-gateways",
    type: "country",
    label: "Mexico gateways",
    // Top 6 Mexican airports by 2024 passenger traffic.
    airports: ["MEX", "CUN", "GDL", "MTY", "TIJ", "SJD"],
  },
  "south-america-gateways": {
    id: "south-america-gateways",
    type: "continent",
    label: "South American gateways",
    // Top 15 South American airports by 2024 passenger traffic.
    airports: [
      "GRU",
      "BOG",
      "LIM",
      "SCL",
      "CGH",
      "GIG",
      "AEP",
      "BSB",
      "MDE",
      "CNF",
      "VCP",
      "EZE",
      "REC",
      "CTG",
      "POA",
    ],
  },
  "africa-gateways": {
    id: "africa-gateways",
    type: "continent",
    label: "Africa gateways",
    // Top 20 airports in the African region by 2024 passenger traffic.
    airports: [
      "CAI",
      "JNB",
      "LPA",
      "TFS",
      "ADD",
      "CMN",
      "CPT",
      "HRG",
      "RAK",
      "ALG",
      "NBO",
      "ACE",
      "TUN",
      "SSH",
      "TFN",
      "LOS",
      "FUE",
      "ABV",
      "DUR",
      "FNC",
    ],
  },
  "east-asia-gateways": {
    id: "east-asia-gateways",
    type: "region",
    label: "East Asia gateways",
    // Top 15 East Asian airports by 2024 passenger traffic.
    airports: [
      "HND",
      "PVG",
      "CAN",
      "ICN",
      "PEK",
      "SZX",
      "TFU",
      "HKG",
      "PKX",
      "CKG",
      "HGH",
      "SHA",
      "KMG",
      "XIY",
      "TPE",
    ],
  },
  "oceania-gateways": {
    id: "oceania-gateways",
    type: "region",
    label: "Oceania (Australia+NZ) gateways",
    // Combined top 10 Australian and New Zealand airports by 2024 passenger traffic.
    airports: [
      "SYD",
      "MEL",
      "BNE",
      "AKL",
      "PER",
      "ADL",
      "CHC",
      "OOL",
      "WLG",
      "CNS",
    ],
  },
  vietnam: {
    id: "vietnam",
    type: "country",
    label: "Vietnam",
    // Top 6 Vietnamese airports by 2024 passenger traffic.
    airports: ["SGN", "HAN", "DAD", "CXR", "PQC", "HPH"],
  },
  "germany-gateways": {
    id: "germany-gateways",
    type: "country",
    label: "Germany gateways",
    // Top 5 German airports by 2024 passenger traffic.
    airports: ["FRA", "MUC", "BER", "DUS", "HAM"],
  },
};

/** Display labels for common gateway airports (used in result rows). */
export const AIRPORT_CITY_LABELS: Record<string, string> = {
  JFK: "New York",
  EWR: "Newark",
  BOS: "Boston",
  IAD: "Washington",
  PHL: "Philadelphia",
  CLT: "Charlotte",
  ATL: "Atlanta",
  MIA: "Miami",
  ORD: "Chicago",
  DTW: "Detroit",
  DFW: "Dallas",
  IAH: "Houston",
  DEN: "Denver",
  LAX: "Los Angeles",
  SFO: "San Francisco",
  SEA: "Seattle",
  PAE: "Everett",
  BFI: "Seattle",
  OAK: "Oakland",
  SJC: "San Jose",
  LAS: "Las Vegas",
  MCO: "Orlando",
  PHX: "Phoenix",
  MSP: "Minneapolis",
  FLL: "Fort Lauderdale",
  LGA: "New York",
  SLC: "Salt Lake City",
  BWI: "Baltimore",
  DCA: "Washington",
  SAN: "San Diego",
  TPA: "Tampa",
  BNA: "Nashville",
  HNL: "Honolulu",
  AUS: "Austin",
  MDW: "Chicago",
  DAL: "Dallas",
  PDX: "Portland",
  STL: "St. Louis",
  RDU: "Raleigh–Durham",
  EZE: "Buenos Aires",
  YYZ: "Toronto",
  YVR: "Vancouver",
  YUL: "Montreal",
  YYC: "Calgary",
  YEG: "Edmonton",
  YOW: "Ottawa",
  LHR: "London",
  LGW: "London",
  LCY: "London",
  SEN: "London",
  DUB: "Dublin",
  MAN: "Manchester",
  STN: "London",
  LTN: "London",
  EDI: "Edinburgh",
  BHX: "Birmingham",
  BRS: "Bristol",
  GLA: "Glasgow",
  CDG: "Paris",
  ORY: "Paris",
  NCE: "Nice",
  MRS: "Marseille",
  LYS: "Lyon",
  AMS: "Amsterdam",
  MAD: "Madrid",
  FRA: "Frankfurt",
  BCN: "Barcelona",
  FCO: "Rome",
  MUC: "Munich",
  LIS: "Lisbon",
  PMI: "Palma de Mallorca",
  ATH: "Athens",
  VIE: "Vienna",
  ZRH: "Zurich",
  CPH: "Copenhagen",
  MXP: "Milan",
  OSL: "Oslo",
  BER: "Berlin",
  AGP: "Malaga",
  BRU: "Brussels",
  ARN: "Stockholm",
  WAW: "Warsaw",
  DUS: "Düsseldorf",
  ALC: "Alicante",
  GVA: "Geneva",
  BUD: "Budapest",
  BGY: "Bergamo",
  PRG: "Prague",
  HEL: "Helsinki",
  OTP: "Bucharest",
  OPO: "Porto",
  NAP: "Naples",
  CTA: "Catania",
  VCE: "Venice",
  KRK: "Kraków",
  VLC: "Valencia",
  BLQ: "Bologna",
  LIN: "Milan",
  MEX: "Mexico City",
  CUN: "Cancún",
  GDL: "Guadalajara",
  MTY: "Monterrey",
  TIJ: "Tijuana",
  SJD: "Los Cabos",
  HAM: "Hamburg",
  GRU: "São Paulo",
  BOG: "Bogotá",
  LIM: "Lima",
  SCL: "Santiago",
  CGH: "São Paulo",
  GIG: "Rio de Janeiro",
  AEP: "Buenos Aires",
  BSB: "Brasília",
  MDE: "Medellín",
  CNF: "Belo Horizonte",
  VCP: "Campinas",
  REC: "Recife",
  CTG: "Cartagena",
  POA: "Porto Alegre",
  HND: "Tokyo",
  NRT: "Tokyo",
  PVG: "Shanghai",
  CAN: "Guangzhou",
  ICN: "Seoul",
  GMP: "Seoul",
  PEK: "Beijing",
  SZX: "Shenzhen",
  TFU: "Chengdu",
  CTU: "Chengdu",
  HKG: "Hong Kong",
  PKX: "Beijing",
  CKG: "Chongqing",
  HGH: "Hangzhou",
  SHA: "Shanghai",
  KMG: "Kunming",
  XIY: "Xi’an",
  TPE: "Taipei",
  CSX: "Changsha",
  CGO: "Zhengzhou",
  NKG: "Nanjing",
  XMN: "Xiamen",
  KWE: "Guiyang",
  HAK: "Haikou",
  CJU: "Jeju",
  KIX: "Osaka",
  TAS: "Tashkent",
  TVT: "Tashkent",
  VOD: "Prague",
  SGN: "Ho Chi Minh City",
  HAN: "Hanoi",
  DAD: "Da Nang",
  CXR: "Nha Trang",
  PQC: "Phu Quoc",
  HPH: "Hai Phong",
  DXB: "Dubai",
  AUH: "Abu Dhabi",
  IST: "Istanbul",
  SAW: "Istanbul",
  AYT: "Antalya",
  DEL: "Delhi",
  BOM: "Mumbai",
  BLR: "Bengaluru",
  SIN: "Singapore",
  KUL: "Kuala Lumpur",
  BKK: "Bangkok",
  DMK: "Bangkok",
  CGK: "Jakarta",
  DOH: "Doha",
  JED: "Jeddah",
  RUH: "Riyadh",
  MNL: "Manila",
  SYD: "Sydney",
  MEL: "Melbourne",
  BNE: "Brisbane",
  AKL: "Auckland",
  PER: "Perth",
  ADL: "Adelaide",
  CHC: "Christchurch",
  OOL: "Gold Coast",
  WLG: "Wellington",
  CNS: "Cairns",
  CAI: "Cairo",
  JNB: "Johannesburg",
  LPA: "Gran Canaria",
  TFS: "Tenerife",
  ADD: "Addis Ababa",
  CMN: "Casablanca",
  CPT: "Cape Town",
  HRG: "Hurghada",
  RAK: "Marrakesh",
  ALG: "Algiers",
  NBO: "Nairobi",
  ACE: "Lanzarote",
  TUN: "Tunis",
  SSH: "Sharm el-Sheikh",
  TFN: "Tenerife",
  LOS: "Lagos",
  FUE: "Fuerteventura",
  ABV: "Abuja",
  DUR: "Durban",
  FNC: "Madeira",
  SVO: "Moscow",
  DME: "Moscow",
  VKO: "Moscow",
  LED: "Saint Petersburg",
  WUH: "Wuhan",
  PTY: "Panama City",
};

export function airportLabel(code: string): string {
  const city = AIRPORT_CITY_LABELS[code];
  return city ? `${city} (${code})` : code;
}
