export type LocationType =
  | "airport"
  | "city"
  | "country"
  | "region"
  | "continent";

export type LocationEntry = {
  id: string;
  type: LocationType;
  label: string;
  /** Direct IATA codes owned by this entry. */
  airports?: string[];
  /** Other registry ids to compose recursively. */
  refs?: string[];
};

/**
 * Composable location registry. "usa" appears only here as registry data.
 * Resolution is recursive with cycle detection (see LocationResolver).
 */
export const LOCATION_REGISTRY: Record<string, LocationEntry> = {
  EZE: {
    id: "EZE",
    type: "airport",
    label: "Buenos Aires (EZE)",
    airports: ["EZE"],
  },
  london: {
    id: "london",
    type: "city",
    label: "London (all airports)",
    airports: ["LHR", "LGW", "STN", "LTN", "LCY", "SEN"],
  },
  seattle: {
    id: "seattle",
    type: "city",
    label: "Seattle (all airports)",
    airports: ["SEA", "PAE", "BFI"],
  },
  "san-francisco": {
    id: "san-francisco",
    type: "city",
    label: "SF (all airports)",
    airports: ["SFO", "OAK", "SJC"],
  },
  "usa-gateways": {
    id: "usa-gateways",
    type: "country",
    label: "USA gateways",
    // Top 35 US airports by 2024 total passenger traffic (ACI-NA).
    airports: [
      "ATL",
      "DFW",
      "DEN",
      "ORD",
      "LAX",
      "JFK",
      "CLT",
      "LAS",
      "MCO",
      "MIA",
      "SEA",
      "PHX",
      "SFO",
      "EWR",
      "IAH",
      "BOS",
      "MSP",
      "FLL",
      "LGA",
      "DTW",
      "PHL",
      "SLC",
      "BWI",
      "IAD",
      "DCA",
      "SAN",
      "TPA",
      "BNA",
      "HNL",
      "AUS",
      "MDW",
      "DAL",
      "PDX",
      "STL",
      "RDU",
    ],
  },
  "canada-gateways": {
    id: "canada-gateways",
    type: "country",
    label: "Canada gateways",
    // Top 6 Canadian airports by 2024 passenger traffic.
    airports: ["YYZ", "YVR", "YUL", "YYC", "YEG", "YOW"],
  },
  "uk-ireland-gateways": {
    id: "uk-ireland-gateways",
    type: "region",
    label: "UK/Ireland gateways",
    // Combined top 10 by 2024 passenger traffic.
    airports: [
      "LHR",
      "LGW",
      "DUB",
      "MAN",
      "STN",
      "LTN",
      "EDI",
      "BHX",
      "BRS",
      "GLA",
    ],
  },
  "schengen-eu-gateways": {
    id: "schengen-eu-gateways",
    type: "region",
    label: "Schengen/EU gateways",
    // Top 40 Schengen-area airports by 2024 passenger traffic.
    airports: [
      "CDG",
      "AMS",
      "MAD",
      "FRA",
      "BCN",
      "FCO",
      "MUC",
      "LIS",
      "PMI",
      "ORY",
      "ATH",
      "VIE",
      "ZRH",
      "CPH",
      "MXP",
      "OSL",
      "BER",
      "AGP",
      "BRU",
      "ARN",
      "WAW",
      "DUS",
      "ALC",
      "GVA",
      "BUD",
      "BGY",
      "PRG",
      "HEL",
      "OTP",
      "OPO",
      "HAM",
      "NCE",
      "NAP",
      "CTA",
      "VCE",
      "MRS",
      "KRK",
      "VLC",
      "BLQ",
      "LIN",
    ],
  },
  "mexico-gateways": {
    id: "mexico-gateways",
    type: "country",
    label: "Mexico gateways",
    // Top 6 Mexican airports by 2024 passenger traffic.
    airports: ["MEX", "CUN", "GDL", "MTY", "TIJ", "SJD"],
  },
  "south-america-gateways": {
    id: "south-america-gateways",
    type: "continent",
    label: "South American gateways",
    // Top 15 South American airports by 2024 passenger traffic.
    airports: [
      "GRU",
      "BOG",
      "LIM",
      "SCL",
      "CGH",
      "GIG",
      "AEP",
      "BSB",
      "MDE",
      "CNF",
      "VCP",
      "EZE",
      "REC",
      "CTG",
      "POA",
    ],
  },
  "east-asia-gateways": {
    id: "east-asia-gateways",
    type: "region",
    label: "East Asia gateways",
    // Top 15 East Asian airports by 2024 passenger traffic.
    airports: [
      "HND",
      "PVG",
      "CAN",
      "ICN",
      "PEK",
      "SZX",
      "TFU",
      "HKG",
      "PKX",
      "CKG",
      "HGH",
      "SHA",
      "KMG",
      "XIY",
      "TPE",
    ],
  },
  "germany-gateways": {
    id: "germany-gateways",
    type: "country",
    label: "Germany gateways",
    // Top 5 German airports by 2024 passenger traffic.
    airports: ["FRA", "MUC", "BER", "DUS", "HAM"],
  },
  "france-gateways": {
    id: "france-gateways",
    type: "country",
    label: "France gateways",
    // Top 5 French airports by 2024 passenger traffic.
    airports: ["CDG", "ORY", "NCE", "MRS", "LYS"],
  },
};

/** Display labels for common gateway airports (used in result rows). */
export const AIRPORT_CITY_LABELS: Record<string, string> = {
  JFK: "New York",
  EWR: "Newark",
  BOS: "Boston",
  IAD: "Washington",
  PHL: "Philadelphia",
  CLT: "Charlotte",
  ATL: "Atlanta",
  MIA: "Miami",
  ORD: "Chicago",
  DTW: "Detroit",
  DFW: "Dallas",
  IAH: "Houston",
  DEN: "Denver",
  LAX: "Los Angeles",
  SFO: "San Francisco",
  SEA: "Seattle",
  PAE: "Everett",
  BFI: "Seattle",
  OAK: "Oakland",
  SJC: "San Jose",
  LAS: "Las Vegas",
  MCO: "Orlando",
  PHX: "Phoenix",
  MSP: "Minneapolis",
  FLL: "Fort Lauderdale",
  LGA: "New York",
  SLC: "Salt Lake City",
  BWI: "Baltimore",
  DCA: "Washington",
  SAN: "San Diego",
  TPA: "Tampa",
  BNA: "Nashville",
  HNL: "Honolulu",
  AUS: "Austin",
  MDW: "Chicago",
  DAL: "Dallas",
  PDX: "Portland",
  STL: "St. Louis",
  RDU: "Raleigh–Durham",
  EZE: "Buenos Aires",
  YYZ: "Toronto",
  YVR: "Vancouver",
  YUL: "Montreal",
  YYC: "Calgary",
  YEG: "Edmonton",
  YOW: "Ottawa",
  LHR: "London",
  LGW: "London",
  LCY: "London",
  SEN: "London",
  DUB: "Dublin",
  MAN: "Manchester",
  STN: "London",
  LTN: "London",
  EDI: "Edinburgh",
  BHX: "Birmingham",
  BRS: "Bristol",
  GLA: "Glasgow",
  CDG: "Paris",
  ORY: "Paris",
  NCE: "Nice",
  MRS: "Marseille",
  LYS: "Lyon",
  AMS: "Amsterdam",
  MAD: "Madrid",
  FRA: "Frankfurt",
  BCN: "Barcelona",
  FCO: "Rome",
  MUC: "Munich",
  LIS: "Lisbon",
  PMI: "Palma de Mallorca",
  ATH: "Athens",
  VIE: "Vienna",
  ZRH: "Zurich",
  CPH: "Copenhagen",
  MXP: "Milan",
  OSL: "Oslo",
  BER: "Berlin",
  AGP: "Malaga",
  BRU: "Brussels",
  ARN: "Stockholm",
  WAW: "Warsaw",
  DUS: "Düsseldorf",
  ALC: "Alicante",
  GVA: "Geneva",
  BUD: "Budapest",
  BGY: "Bergamo",
  PRG: "Prague",
  HEL: "Helsinki",
  OTP: "Bucharest",
  OPO: "Porto",
  NAP: "Naples",
  CTA: "Catania",
  VCE: "Venice",
  KRK: "Kraków",
  VLC: "Valencia",
  BLQ: "Bologna",
  LIN: "Milan",
  MEX: "Mexico City",
  CUN: "Cancún",
  GDL: "Guadalajara",
  MTY: "Monterrey",
  TIJ: "Tijuana",
  SJD: "Los Cabos",
  HAM: "Hamburg",
  GRU: "São Paulo",
  BOG: "Bogotá",
  LIM: "Lima",
  SCL: "Santiago",
  CGH: "São Paulo",
  GIG: "Rio de Janeiro",
  AEP: "Buenos Aires",
  BSB: "Brasília",
  MDE: "Medellín",
  CNF: "Belo Horizonte",
  VCP: "Campinas",
  REC: "Recife",
  CTG: "Cartagena",
  POA: "Porto Alegre",
  HND: "Tokyo",
  PVG: "Shanghai",
  CAN: "Guangzhou",
  ICN: "Seoul",
  PEK: "Beijing",
  SZX: "Shenzhen",
  TFU: "Chengdu",
  HKG: "Hong Kong",
  PKX: "Beijing",
  CKG: "Chongqing",
  HGH: "Hangzhou",
  SHA: "Shanghai",
  KMG: "Kunming",
  XIY: "Xi’an",
  TPE: "Taipei",
};

export function airportLabel(code: string): string {
  const city = AIRPORT_CITY_LABELS[code];
  return city ? `${city} (${code})` : code;
}
